# Generated by Django 4.1.5 on 2023-01-29 22:43

from django.db import migrations


def populate_status(apps, schemaeditor):
    statuses = {
        'to do': 'An issue that has not yet been started',
        'in progress': 'An issue in active development',
        'done': 'An issue that has been marked as complete'
    }
    Status = apps.get_model('issues', 'Status')
    for name, desc in statuses.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20230122_1744'),
    ]

    operations = [migrations.RunPython(populate_status)]
